language: node_js
node_js:
  - 14 # latest: 8/27
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - cd themes/suka
  - yarn
  - cd ../..
  - yarn
  - hexo generate # generate static files
deploy:
  provider: pages
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
